version: '3.8'

services:
  nest-app:
    build: .
    container_name: socket-bridge-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/indexer-db
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
